Null color picker
marcusolsson/grafana-hourly-heatmap-panel pull request #24
Opened 2021-03-25 18:12 UTC by KatrinaTurner

Allows you to choose what color is used to fill buckets in the heatmap that have NO data as opposed to data values of 0.

2021-03-25 18:59 UTC, marcusolsson reviewed
Nice! Looks really clean 👍 

I'll make sure to test this during the weekend so we can get this merged! In the meantime, would you mind adding docs for this in the README?

Also, did you make any changes to the .gitignore? Seems to be only whitespace changes? If this was unintentional, could you revert it?

2021-03-25 18:59 UTC, marcusolsson commented on src/module.ts
> +            name: 'Null Value Color',
```suggestion
            name: 'Null value color',
```

For consistency; Other options are in sentence case. Also, I'm wondering if the name alone is clear enough or whether it warrants a description. We could also wait to collect feedback.

2021-03-25 18:59 UTC, marcusolsson commented on src/module.ts
> +          .addColorPicker({
We need to check in which version of Grafana the color picker option was added. Currently, the plugin can run on >=7.0.3, but we might need to bump the required minimum required version depending on when this was introduced.

2021-03-25 19:35 UTC, KatrinaTurner commented
Thank you!  I added a description into the README and reverted the .gitignore changes, they were unintentional.

2021-04-05 06:53 UTC, marcusolsson requested changes
I've tested this and it seems to work great even on 7.0.3, so no version bump needed! 🎉 

It seems like your editor might change the whitespace in the edited files (like the README.md and gitignore). Are you perhaps using Windows? I'm not entirely sure, but your git client might be set up to [commit Windows-style line endings](https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings).

I recommend that you look into it to make it easier to work on cross-platform projects. But if you don't have the time to look into it right now, you could revert the README.md changes and I'll add your docs update in a separate commit.

2021-04-09 00:23 UTC, KatrinaTurner commented
Hi! Yes I am on Windows, I forgot to change the settings for the line endings.  Sorry about that!  I just fixed it and pushed.
Yay! Glad it works on 7.0.3! :)

2021-04-09 06:24 UTC, marcusolsson approved these changes
Thank you for this! 🎉

2021-04-09 06:25 UTC, merged